server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/planify
    username: postgres
    password: 1203
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

jwt:
  secret: 123412341234
  expiration: 86400000
